services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: UW_wordle_07
      MYSQL_DATABASE: UWwordle
      MYSQL_ROOT_HOST: '%'
    volumes:
      - wordlevolume:/var/lib/mysql
    ports:
      - "53306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: UW_wordle_07
    ports:
      - "50080:80"
volumes:
  wordlevolume:
